import { Product, Service, Barber, TicketConfig, Sale } from '../types';

export const INITIAL_TICKET_CONFIG: TicketConfig = {
  businessName: 'BARBAS CUTS',
  subName: 'BARBER STUDIO',
  address: 'Calle Cipreses mz21 lt12, Los Reyes Acaquilpan, México, 56420',
  phone: '55 1234 5678',
  instagram: 'barbas_cuts',
  footerMessage: '¡Gracias por visitarnos! Luce tu mejor estilo.',
  logoUrl: '/images/logo_barbas_cuts.svg',
  showCourtesyOnTicket: true,
  showBarberName: true,
};

export const INITIAL_BARBERS: Barber[] = [
  { id: 'b1', name: 'Carlos "Barbas"', avatar: '🧔🏻‍♂️', active: true },
  { id: 'b2', name: 'Alex "Fade Master"', avatar: '💈', active: true },
  { id: 'b3', name: 'Mateo Studio', avatar: '✂️', active: true },
  { id: 'b4', name: 'David Barber', avatar: '🔥', active: true },
];

export const INITIAL_SERVICES: Service[] = [
  {
    id: 's1',
    name: 'Corte Skin Fade VIP',
    description: 'Corte de cabello personalizado con lavado, peinado con pomada y toalla caliente',
    price: 250,
    durationMinutes: 45,
    imageUrl: '/images/corte_skin_fade.png',
    category: 'Cortes',
    active: true,
    barberCommissionType: 'PERCENTAGE',
    barberCommissionValue: 50, // 50% = $125.00 comisión
  },
  {
    id: 's2',
    name: 'Arreglo de Barba Spa',
    description: 'Perfilado de barba con navaja libre, aceite esencial, vapor ozono y toalla caliente',
    price: 180,
    durationMinutes: 30,
    imageUrl: '/images/arreglo_barba_spa.png',
    category: 'Barba',
    active: true,
    barberCommissionType: 'PERCENTAGE',
    barberCommissionValue: 50, // 50% = $90.00 comisión
  },
  {
    id: 's3',
    name: 'Combo Rey Barbas (Corte + Barba)',
    description: 'Servicio completo VIP: Corte de cabello + Arreglo de barba spa + Masaje relajante facial',
    price: 380,
    durationMinutes: 75,
    imageUrl: '/images/corte_skin_fade.png',
    category: 'Combos',
    active: true,
    barberCommissionType: 'PERCENTAGE',
    barberCommissionValue: 50, // 50% = $190.00 comisión
  },
  {
    id: 's4',
    name: 'Exfoliación & Mascarilla Negra',
    description: 'Limpieza facial profunda, eliminación de puntos negros e hidratación',
    price: 150,
    durationMinutes: 25,
    imageUrl: '/images/arreglo_barba_spa.png',
    category: 'Facial',
    active: true,
    barberCommissionType: 'PERCENTAGE',
    barberCommissionValue: 40, // 40% = $60.00 comisión
  },
  {
    id: 's5',
    name: 'Tinte de Barba o Cabello',
    description: 'Pigmentación uniforme para barba o disimulo de canas en cabello',
    price: 200,
    durationMinutes: 35,
    imageUrl: '/images/corte_skin_fade.png',
    category: 'Color',
    active: true,
    barberCommissionType: 'PERCENTAGE',
    barberCommissionValue: 50, // 50% = $100.00 comisión
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Pomada Mate Barbas Cuts (100g)',
    description: 'Fijación fuerte y acabado mate natural sin residuos grasos',
    price: 220,
    cost: 95,
    stock: 24,
    minStock: 5,
    imageUrl: '/images/pomada_mate.png',
    category: 'Peinado',
    isBeverage: false,
    active: true,
    createdAt: new Date().toISOString(),
    barberCommissionType: 'FIXED',
    barberCommissionValue: 40, // $40.00 por pomada vendida
  },
  {
    id: 'p2',
    name: 'Aceite para Barba Aurum Gold (30ml)',
    description: 'Nutrición con aceite de argán, sándalo y ámbar para suavizar e hidratar la barba',
    price: 290,
    cost: 120,
    stock: 15,
    minStock: 3,
    imageUrl: '/images/aceite_barba.png',
    category: 'Cuidado Barba',
    isBeverage: false,
    active: true,
    createdAt: new Date().toISOString(),
    barberCommissionType: 'FIXED',
    barberCommissionValue: 50, // $50.00 por aceite vendido
  },
  {
    id: 'p3',
    name: 'Bálsamo Crecimiento & Estilo (60g)',
    description: 'Hidrata la piel de la cara y moldea los vellos rebeldes de la barba',
    price: 240,
    cost: 100,
    stock: 8,
    minStock: 4,
    imageUrl: '/images/pomada_mate.png',
    category: 'Cuidado Barba',
    isBeverage: false,
    active: true,
    createdAt: new Date().toISOString(),
    barberCommissionType: 'FIXED',
    barberCommissionValue: 40,
  },

  // BEVERAGES / BEBIDAS
  {
    id: 'b_bev1',
    name: 'Whiskey Bourbon en las Rocas',
    description: 'Vaso de whiskey en las rocas de la casa. Puede ofrecerse como cortesía o venta',
    price: 90,
    cost: 35,
    stock: 30,
    minStock: 10,
    imageUrl: '/images/whiskey.png',
    category: 'Bebidas',
    isBeverage: true,
    active: true,
    createdAt: new Date().toISOString(),
    barberCommissionType: 'FIXED',
    barberCommissionValue: 15,
  },
  {
    id: 'b_bev2',
    name: 'Cerveza Artesanal Pale Ale (355ml)',
    description: 'Cerveza helada estilo Pale Ale para acompañar tu servicio',
    price: 65,
    cost: 25,
    stock: 45,
    minStock: 12,
    imageUrl: '/images/cerveza.png',
    category: 'Bebidas',
    isBeverage: true,
    active: true,
    createdAt: new Date().toISOString(),
    barberCommissionType: 'FIXED',
    barberCommissionValue: 10,
  },
  {
    id: 'b_bev3',
    name: 'Café Espresso Doble',
    description: 'Café de grano selecto recién molido',
    price: 45,
    cost: 12,
    stock: 60,
    minStock: 15,
    imageUrl: '/images/whiskey.png',
    category: 'Bebidas',
    isBeverage: true,
    active: true,
    createdAt: new Date().toISOString(),
    barberCommissionType: 'FIXED',
    barberCommissionValue: 5,
  },
  {
    id: 'b_bev4',
    name: 'Refresco Coca Cola (355ml)',
    description: 'Lata de refresco helado',
    price: 35,
    cost: 14,
    stock: 50,
    minStock: 15,
    imageUrl: '/images/cerveza.png',
    category: 'Bebidas',
    isBeverage: true,
    active: true,
    createdAt: new Date().toISOString(),
    barberCommissionType: 'FIXED',
    barberCommissionValue: 5,
  },
  {
    id: 'b_bev5',
    name: 'Agua Mineral de Manantial (500ml)',
    description: 'Agua mineral gasificada helada',
    price: 30,
    cost: 10,
    stock: 40,
    minStock: 10,
    imageUrl: '/images/whiskey.png',
    category: 'Bebidas',
    isBeverage: true,
    active: true,
    createdAt: new Date().toISOString(),
    barberCommissionType: 'FIXED',
    barberCommissionValue: 5,
  },
];

export const INITIAL_SALES: Sale[] = [];

export const INITIAL_APPOINTMENTS = [
  {
    id: 'apt-1',
    customerName: 'Fernando Gómez',
    customerPhone: '55 9876 5432',
    barberId: 'b1',
    barberName: 'Carlos "Barbas"',
    serviceId: 's3',
    serviceName: 'Combo Rey Barbas (Corte + Barba)',
    servicePrice: 380,
    date: new Date().toISOString().split('T')[0],
    time: '15:30',
    status: 'CONFIRMADA' as const,
    notes: 'Cliente VIP, pide toalla caliente extra',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'apt-2',
    customerName: 'Roberto Mendoza',
    customerPhone: '55 1122 3344',
    barberId: 'b2',
    barberName: 'Alex "Fade Master"',
    serviceId: 's1',
    serviceName: 'Corte Skin Fade VIP',
    servicePrice: 250,
    date: new Date().toISOString().split('T')[0],
    time: '17:00',
    status: 'PENDIENTE' as const,
    notes: 'Primera cita',
    createdAt: new Date().toISOString(),
  },
];
